import sys
import os
import re
import argparse

def search_protos(proto_path):
    protos = []
    for root, dirs, files in os.walk(proto_path):
        for file in files:
            if file.endswith(".proto"):
                protos.append(os.path.join(root, file))
    return protos


def main():
    # parse arguments
    parser = argparse.ArgumentParser(description="Generate TS code from protobuf file")
    parser.add_argument("--proto", help="Path to protobuf file", required=True)
    parser.add_argument("--out", help="Output directory", required=True)
    args = parser.parse_args()

    print("Generating TS code from %s to %s" % (args.proto, args.out))

    command_matcher = re.compile(r"message\s+(\w+Msg)\s+{")
    command_id_matcher = re.compile(r"\s+option\s+\(msg_id\)\s+=\s+(\d+);")

    # read proto file
    proto_lines = []
    proto_names = []
    # for each .proto file
    for proto_file in search_protos(args.proto):
        # skip common.proto
        if "common.proto" in proto_file:
            continue

        with open(proto_file, "r") as f:
            proto_lines += f.readlines()
            proto_names.append(proto_file.split("/")[-1].split(".")[0])

    cs_file_content = f"""
// Code generated by message-interface-generator.py. DO NOT EDIT.
import * as jspb from "google-protobuf";
        """
    # for each filename
    for proto_name in proto_names:
        cs_file_content += f"""
import * as {proto_name} from './{proto_name}_pb';
        """


    # extract message names including "Command" suffix using regex
    command_names = [command_matcher.match(line).group(1) for line in proto_lines if command_matcher.match(line)]
    # extract command ids using regex
    command_ids = [command_id_matcher.match(line).group(1) for line in proto_lines if
                   command_id_matcher.match(line)]
    if len(command_names) == 0:
        sys.exit(0)

    if len(command_names) != len(command_ids):
        print("Error: number of commands and command ids must be equal (%d, %d, %d)" % (
            len(command_names), len(command_ids)))
        sys.exit(1)

    cs_file_content += """
export function GetMessageID(msg: jspb.Message): number {
    switch (msg.constructor) {
    """
    for i in range(len(command_names)):
        cs_file_content += f"""
        case {proto_names[0]}.{command_names[i]}.prototype.constructor:
            return {command_ids[i]}
        """
    cs_file_content += """
        default:
            return -1
    }
}
    """

        # generate the factory from command id and byte array
    cs_file_content += """
export function Create(id: number, data: Uint8Array): jspb.Message | null {
    switch (id) {
        """
    for i in range(len(command_names)):
        cs_file_content += f"""
        case {command_ids[i]}:
            return {proto_names[0]}.{command_names[i]}.deserializeBinary(data)
        """
    cs_file_content += """
        default:
            return null
    }
}
        """

    # write Go code to file
    with open(args.out, "w") as f:
        f.write(cs_file_content)


if __name__ == "__main__":
    main()
