
// Code generated by message-interface-generator.py. DO NOT EDIT.
package pb
        
var JoinMatchmakingMsgId = byte(1)

func (m *JoinMatchmakingMsg) Id() byte {
    return 1
}
func (m *JoinMatchmakingMsg) New() Msg {
    return &JoinMatchmakingMsg{}
}
var MatchmakingStatusMsgId = byte(2)

func (m *MatchmakingStatusMsg) Id() byte {
    return 2
}
func (m *MatchmakingStatusMsg) New() Msg {
    return &MatchmakingStatusMsg{}
}
var CompleteMatchmakingMsgId = byte(3)

func (m *CompleteMatchmakingMsg) Id() byte {
    return 3
}
func (m *CompleteMatchmakingMsg) New() Msg {
    return &CompleteMatchmakingMsg{}
}
var BattleInitDataMsgId = byte(4)

func (m *BattleInitDataMsg) Id() byte {
    return 4
}
func (m *BattleInitDataMsg) New() Msg {
    return &BattleInitDataMsg{}
}
var BattleClientEntityUpdateMsgId = byte(5)

func (m *BattleClientEntityUpdateMsg) Id() byte {
    return 5
}
func (m *BattleClientEntityUpdateMsg) New() Msg {
    return &BattleClientEntityUpdateMsg{}
}
var BattleServerEntityUpdateMsgId = byte(6)

func (m *BattleServerEntityUpdateMsg) Id() byte {
    return 6
}
func (m *BattleServerEntityUpdateMsg) New() Msg {
    return &BattleServerEntityUpdateMsg{}
}
var BattleClientCheckpointUpdateMsgId = byte(7)

func (m *BattleClientCheckpointUpdateMsg) Id() byte {
    return 7
}
func (m *BattleClientCheckpointUpdateMsg) New() Msg {
    return &BattleClientCheckpointUpdateMsg{}
}
var BattleServerCheckpointUpdateMsgId = byte(8)

func (m *BattleServerCheckpointUpdateMsg) Id() byte {
    return 8
}
func (m *BattleServerCheckpointUpdateMsg) New() Msg {
    return &BattleServerCheckpointUpdateMsg{}
}
var BattleClientPlayerFinishMsgId = byte(9)

func (m *BattleClientPlayerFinishMsg) Id() byte {
    return 9
}
func (m *BattleClientPlayerFinishMsg) New() Msg {
    return &BattleClientPlayerFinishMsg{}
}
var BattleServerPlayerFinishMsgId = byte(10)

func (m *BattleServerPlayerFinishMsg) Id() byte {
    return 10
}
func (m *BattleServerPlayerFinishMsg) New() Msg {
    return &BattleServerPlayerFinishMsg{}
}
var BattleFinishMsgId = byte(11)

func (m *BattleFinishMsg) Id() byte {
    return 11
}
func (m *BattleFinishMsg) New() Msg {
    return &BattleFinishMsg{}
}
func Create(id byte) Msg {
        switch id {
                           
    case 1:
        return &JoinMatchmakingMsg{}
        
    case 2:
        return &MatchmakingStatusMsg{}
        
    case 3:
        return &CompleteMatchmakingMsg{}
        
    case 4:
        return &BattleInitDataMsg{}
        
    case 5:
        return &BattleClientEntityUpdateMsg{}
        
    case 6:
        return &BattleServerEntityUpdateMsg{}
        
    case 7:
        return &BattleClientCheckpointUpdateMsg{}
        
    case 8:
        return &BattleServerCheckpointUpdateMsg{}
        
    case 9:
        return &BattleClientPlayerFinishMsg{}
        
    case 10:
        return &BattleServerPlayerFinishMsg{}
        
    case 11:
        return &BattleFinishMsg{}
        
    default:
        return nil
    }
}
        