name: kart-server
services:
  kart-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9100:8080"
    environment:
      - CONFIG_LEADERBOARD_REDISENDPOINT=kart-redis:6379
    restart: unless-stopped
  kart-redis:
    image: redis:alpine
    volumes:
      - kart-redis-data:/data
volumes:
    kart-redis-data: