// source: game.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.kart.BattleEntity');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.kart.Vector3');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kart.BattleEntity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kart.BattleEntity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kart.BattleEntity.displayName = 'proto.kart.BattleEntity';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kart.BattleEntity.prototype.toObject = function(opt_includeInstance) {
  return proto.kart.BattleEntity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kart.BattleEntity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kart.BattleEntity.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    position: (f = msg.getPosition()) && proto.kart.Vector3.toObject(includeInstance, f),
    rotation: (f = msg.getRotation()) && proto.kart.Vector3.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.kart.Vector3.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kart.BattleEntity}
 */
proto.kart.BattleEntity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kart.BattleEntity;
  return proto.kart.BattleEntity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kart.BattleEntity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kart.BattleEntity}
 */
proto.kart.BattleEntity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.kart.Vector3;
      reader.readMessage(value,proto.kart.Vector3.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 3:
      var value = new proto.kart.Vector3;
      reader.readMessage(value,proto.kart.Vector3.deserializeBinaryFromReader);
      msg.setRotation(value);
      break;
    case 4:
      var value = new proto.kart.Vector3;
      reader.readMessage(value,proto.kart.Vector3.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kart.BattleEntity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kart.BattleEntity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kart.BattleEntity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kart.BattleEntity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.kart.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getRotation();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.kart.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.kart.Vector3.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.kart.BattleEntity.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.kart.BattleEntity} returns this
 */
proto.kart.BattleEntity.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Vector3 position = 2;
 * @return {?proto.kart.Vector3}
 */
proto.kart.BattleEntity.prototype.getPosition = function() {
  return /** @type{?proto.kart.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.kart.Vector3, 2));
};


/**
 * @param {?proto.kart.Vector3|undefined} value
 * @return {!proto.kart.BattleEntity} returns this
*/
proto.kart.BattleEntity.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kart.BattleEntity} returns this
 */
proto.kart.BattleEntity.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kart.BattleEntity.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Vector3 rotation = 3;
 * @return {?proto.kart.Vector3}
 */
proto.kart.BattleEntity.prototype.getRotation = function() {
  return /** @type{?proto.kart.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.kart.Vector3, 3));
};


/**
 * @param {?proto.kart.Vector3|undefined} value
 * @return {!proto.kart.BattleEntity} returns this
*/
proto.kart.BattleEntity.prototype.setRotation = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kart.BattleEntity} returns this
 */
proto.kart.BattleEntity.prototype.clearRotation = function() {
  return this.setRotation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kart.BattleEntity.prototype.hasRotation = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vector3 velocity = 4;
 * @return {?proto.kart.Vector3}
 */
proto.kart.BattleEntity.prototype.getVelocity = function() {
  return /** @type{?proto.kart.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.kart.Vector3, 4));
};


/**
 * @param {?proto.kart.Vector3|undefined} value
 * @return {!proto.kart.BattleEntity} returns this
*/
proto.kart.BattleEntity.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kart.BattleEntity} returns this
 */
proto.kart.BattleEntity.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kart.BattleEntity.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 4) != null;
};


