
// Code generated by message-interface-generator.py. DO NOT EDIT.
import * as jspb from "google-protobuf";
        
import * as game from './game_pb';
        
export function GetMessageID(msg: jspb.Message): number {
    switch (msg.constructor) {
    
        case game.JoinMatchmakingMsg.prototype.constructor:
            return 1
        
        case game.MatchmakingStatusMsg.prototype.constructor:
            return 2
        
        case game.CompleteMatchmakingMsg.prototype.constructor:
            return 3
        
        case game.BattleInitDataMsg.prototype.constructor:
            return 4
        
        case game.BattleClientEntityUpdateMsg.prototype.constructor:
            return 5
        
        case game.BattleServerEntityUpdateMsg.prototype.constructor:
            return 6
        
        case game.BattleClientCheckpointUpdateMsg.prototype.constructor:
            return 7
        
        case game.BattleServerCheckpointUpdateMsg.prototype.constructor:
            return 8
        
        case game.BattleClientPlayerFinishMsg.prototype.constructor:
            return 9
        
        case game.BattleServerPlayerFinishMsg.prototype.constructor:
            return 10
        
        case game.BattleFinishMsg.prototype.constructor:
            return 11
        
        case game.BattleHeartbeatMsg.prototype.constructor:
            return 12
        
        case game.BattleClientReadyMsg.prototype.constructor:
            return 13
        
        case game.BattleStateUpdateMsg.prototype.constructor:
            return 14
        
        case game.LeaveMatchmakingMsg.prototype.constructor:
            return 15
        
        default:
            return -1
    }
}
    
export function Create(id: number, data: Uint8Array): jspb.Message | null {
    switch (id) {
        
        case 1:
            return game.JoinMatchmakingMsg.deserializeBinary(data)
        
        case 2:
            return game.MatchmakingStatusMsg.deserializeBinary(data)
        
        case 3:
            return game.CompleteMatchmakingMsg.deserializeBinary(data)
        
        case 4:
            return game.BattleInitDataMsg.deserializeBinary(data)
        
        case 5:
            return game.BattleClientEntityUpdateMsg.deserializeBinary(data)
        
        case 6:
            return game.BattleServerEntityUpdateMsg.deserializeBinary(data)
        
        case 7:
            return game.BattleClientCheckpointUpdateMsg.deserializeBinary(data)
        
        case 8:
            return game.BattleServerCheckpointUpdateMsg.deserializeBinary(data)
        
        case 9:
            return game.BattleClientPlayerFinishMsg.deserializeBinary(data)
        
        case 10:
            return game.BattleServerPlayerFinishMsg.deserializeBinary(data)
        
        case 11:
            return game.BattleFinishMsg.deserializeBinary(data)
        
        case 12:
            return game.BattleHeartbeatMsg.deserializeBinary(data)
        
        case 13:
            return game.BattleClientReadyMsg.deserializeBinary(data)
        
        case 14:
            return game.BattleStateUpdateMsg.deserializeBinary(data)
        
        case 15:
            return game.LeaveMatchmakingMsg.deserializeBinary(data)
        
        default:
            return null
    }
}
        